### ISSUE TITLE
Rendering artifacts 8u60 + Marlin 0.7.0-Unsafe

### ISSUE THREAD

**Issue by jandam** [bourgesl/marlin-renderer#4]
Hi,

  I've experienced rendering artifacts when I was testing Martin 0.7.0. After enabling checks in Marlin I get following exception. My code draws/fill GlyphVector to g2 from BufferedImage.

        FontRenderContext fontRenderContext = new FontRenderContext(new AffineTransform(), true, true);
            GlyphVector gv = font.createGlyphVector(fontRenderContext, <text>);

                Shape outline = gv.getOutline();
                if (symbolizer.getHaloFill() != null && symbolizer.getHaloRadius() > 0.0) {
                    g2.setColor(Color.WHITE);
                    g2.setStroke(new BasicStroke(4.0, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND);
                    g2.draw(outline);
                }
                g2.setColor(Color.BLACK);
                g2.fill(outline);

java.lang.Throwable
        at org.marlin.pisces.IntArrayCache.check(IntArrayCache.java:135)
        at org.marlin.pisces.IntArrayCache.fill(IntArrayCache.java:124)
        at org.marlin.pisces.Renderer.dispose(Renderer.java:672)
        at org.marlin.pisces.MarlinRenderingEngine.getAATileGenerator(MarlinRenderingEngine.java:724)
        at sun.java2d.pipe.AAShapePipe.renderPath(AAShapePipe.java:152)
        at sun.java2d.pipe.AAShapePipe.fill(AAShapePipe.java:68)
        at sun.java2d.pipe.PixelToParallelogramConverter.fill(PixelToParallelogramConverter.java:164)
        at sun.java2d.SunGraphics2D.fill(SunGraphics2D.java:2527)
WARNING: Invalid array value at 2048

...

java.lang.Throwable
        at org.marlin.pisces.IntArrayCache.check(IntArrayCache.java:135)
        at org.marlin.pisces.IntArrayCache.fill(IntArrayCache.java:124)
        at org.marlin.pisces.Renderer.dispose(Renderer.java:672)
        at org.marlin.pisces.MarlinRenderingEngine.getAATileGenerator(MarlinRenderingEngine.java:724)
        at sun.java2d.pipe.AAShapePipe.renderPath(AAShapePipe.java:152)
        at sun.java2d.pipe.AAShapePipe.draw(AAShapePipe.java:64)
        at sun.java2d.pipe.PixelToParallelogramConverter.draw(PixelToParallelogramConverter.java:148)
        at sun.java2d.SunGraphics2D.draw(SunGraphics2D.java:2497)

INFO: ===============================================================================
INFO: Marlin software rasterizer           = ENABLED
INFO: Version                              = [marlin-0.7.0-Unsafe]
INFO: sun.java2d.renderer                  = org.marlin.pisces.MarlinRenderingEngine
INFO: sun.java2d.renderer.useThreadLocal   = true
INFO: sun.java2d.renderer.useRef           = soft
INFO: sun.java2d.renderer.pixelsize        = 2048
INFO: sun.java2d.renderer.subPixel_log2_X  = 3
INFO: sun.java2d.renderer.subPixel_log2_Y  = 3
INFO: sun.java2d.renderer.tileSize_log2    = 5
INFO: sun.java2d.renderer.useSimplifier    = false
INFO: sun.java2d.renderer.doStats          = false
INFO: sun.java2d.renderer.doMonitors       = false
INFO: sun.java2d.renderer.doChecks         = true
INFO: sun.java2d.renderer.useLogger        = false
INFO: sun.java2d.renderer.logCreateContext = false
INFO: sun.java2d.renderer.logUnsafeMalloc  = false
INFO: Renderer settings:
INFO: CUB_COUNT_LG = 2
INFO: CUB_DEC_BND  = 20.0
INFO: CUB_INC_BND  = 8.0
INFO: QUAD_DEC_BND = 8.0
INFO: sun.java2d.renderer.gamma            = 1.0
INFO: ===============================================================================

**Comment by jandam** [comment]
Sorry, already fixed in Marlin 0.7.0.1

**Comment by bourgesl** [comment]
Thanks anyway for your bug report.

I have to post an annoucement for the Marlin 0.7.0.1 (bug fixes)
